### ISSUE TITLE
strtoupper() expects parameter 1 to be string

### ISSUE THREAD

**Issue by janwas** [paynl/virtuemart3-plugin#1]
hi,
when doing a payment, I get a PHP warning in the server log with description "strtoupper() expects parameter 1 to be string" in api/Start.php, line 37
Line 37: $this->_currency = strtoupper($currency);

The payment goes ok, but it may be better to prevent this warning.
What do you think?

btw, I run version 3.3.8.

regards, jan

**Comment by woutse** [comment]
Dear Jan, 

In the meanwhile this issue has been fixed. Thanks for reporting!
